[application]

name = "Structuraa"

default_platform = "desktop"

out_dir = "dist"

asset_dir = "public"

[web.app]

title = "Structuraa"

[web.watcher]

reload_html = true

watch_path = ["src", "assets"]

[web.resource]

style = []

script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []